Default: &defaults
    database: velouria.sqlite3
    poolsize: 10

Development:
    <<: *defaults

Testing:
    database: velouria_test.sqlite3
    <<: *defaults

Staging:
    database: velouria_staging.sqlite3
    poolsize: 100
    <<: *defaults

Production:
    database: velouria_production.sqlite3
    poolsize: 100
    <<: *defaults
