ForumName: Forum name
TopicName: Topic name
LastPost: Last Post
LastTopic: Last Topic
ForaList: List of fora
TopicList: List of topics
EmptyForum: Threre aren’t any messages in this forum.
NoFora: There aren’t any fora yet.
CreateTopicLink: Create a topic
CreateForumLink: Create a forum
TopicCount: Topics
RepliesCount: Replies

#Form
ParentForum: Parent forum
ForumTitle: Title
ForumSlug: Slug
ForumDescription: Description

#Navbar
LogOut: Log out
LogIn: Log in

# Create Forum
ForumCreationTitle: Create a new forum
CreateForum: Create

# View Topic
BackToForum forumTitle@Text: Back to #{forumTitle}

# Create Topic
TopicTitle: Title
TopicSlug: Slug
TopicBody: Content
CreateTopic: Create
NoAnonymousTopics: You have to be signed in to create topics.

# Reply
ReplyTitle topicTitle@Text: Reply to #{topicTitle}
ReplyBody: Content
ReplyButton: Reply
